### 7.	Write Python program using NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a = np.zeros(4)
print(a)
print("Data Type:",a.dtype)

a = np.ones(4)
print("\n",a)
print("Data Type:",a.dtype)

a = np.arange(4)
print("\n",a)
print("Data Type:",a.dtype)

a = np.linspace(0, 4, num=8)
print("\n",a)
print("Data Type:",a.dtype)

[0. 0. 0. 0.]
Data Type: float64

 [1. 1. 1. 1.]
Data Type: float64

 [0 1 2 3]
Data Type: int32

 [0.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]
Data Type: float64


In [4]:
b = a.ravel()
b[0] = 3
print(b)
print(a)

[3.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]
[3.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]


In [5]:
b = a.flatten()
b[0] = 5
print(b)
print(a)

[5.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]
[3.         0.57142857 1.14285714 1.71428571 2.28571429 2.85714286
 3.42857143 4.        ]


In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(np.mean(a, axis=0)) 

[4. 5. 6.]


In [8]:
print(np.mean(a, axis=1)) 

[2. 5. 8.]


In [9]:
print(np.mean(a)) 

5.0


In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


#### a)	To find the addition of two matrices

In [11]:
print ("Addition: ")
print (np.add(a,b))
print(a+b)

Addition: 
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [12]:
print ("Subtraction: ")
print (np.subtract(a,b))
print()
print(a-b)
print(b-a)

Subtraction: 
[[-4 -4]
 [-4 -4]]

[[-4 -4]
 [-4 -4]]
[[4 4]
 [4 4]]


#### b) To find the product of two matrices


In [13]:
print ("Multiplication : ")
print (np.multiply(a,b))
print(a*b)

Multiplication : 
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [14]:
print("Dot product :")
print(np.dot(a,b))
print("Matrix multiplication :")
print(np.matmul(a,b))

Dot product :
[[19 22]
 [43 50]]
Matrix multiplication :
[[19 22]
 [43 50]]


In [15]:
print ("Division : ")
print (np.divide(a,b))
print()
print(a/b)
print(b/a)

Division : 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[5.         3.        ]
 [2.33333333 2.        ]]


#### c) To find the transpose of a matrix

In [16]:
print(a.T)

[[1 3]
 [2 4]]


In [17]:
print(b.T)

[[5 7]
 [6 8]]


## 8.	Write python program using Pandas

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("ab - Sheet1.csv")
print(df.shape)
df.head()

(22, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#### a.	To count the NaN values in a dataset.

In [20]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age             3
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          16
Embarked        0
dtype: int64

In [21]:
df.notnull().sum()

PassengerId    22
Survived       22
Pclass         22
Name           22
Sex            22
Age            19
SibSp          22
Parch          22
Ticket         22
Fare           22
Cabin           6
Embarked       22
dtype: int64

#### b. To handle missing values in a dataset.

In [22]:
#Drop All Rows with any Null/NaN/NaT Values

a = df.dropna()
print(a.shape)
a

(6, 12)


PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   
21           22         1       2   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
21                              Beesley, Mr. Lawrence    male  34.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
6       0     17463  51.8625   E46        S  
10      1   PP 9549  16.7000    G6        S  
11      0    113783  26.5500  C103        S  
21      0    248698  13.0000   D56        S

In [23]:
#Drop All Columns with Any Missing Value

b = df.dropna(axis=1)
print(b.shape)
b.head()

(22, 10)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                           Allen, Mr. William Henry    male      0      0   

             Ticket     Fare Embarked  
0         A/5 21171   7.2500        S  
1          PC 17599  71.2833        C  
2  STON/O2. 3101282   7.9250        S  
3            113803  53.1000        S  
4            373450   8.0500        S

In [24]:
#Drop Row/Column Only if All the Values are Null

c = df[df.isna().any(axis=1)]
c

PassengerId  Survived  Pclass  \
0             1         0       3   
2             3         1       3   
4             5         0       3   
5             6         0       3   
7             8         0       3   
8             9         1       3   
9            10         1       2   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   
20                               Fynney, Mr. Joseph J    male  35.0      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
2       0  STON/O2. 3101282   7.9250   NaN        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C  
20      0            239865  26.0000   NaN        S

In [25]:
c1 = c.dropna(how='all', axis=1)
print(c1.shape)
c1.head()

(16, 11)


PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male   
2            3         1       3          Heikkinen, Miss. Laina  female   
4            5         0       3        Allen, Mr. William Henry    male   
5            6         0       3                Moran, Mr. James    male   
7            8         0       3  Palsson, Master. Gosta Leonard    male   

    Age  SibSp  Parch            Ticket     Fare Embarked  
0  22.0      1      0         A/5 21171   7.2500        S  
2  26.0      0      0  STON/O2. 3101282   7.9250        S  
4  35.0      0      0            373450   8.0500        S  
5   NaN      0      0            330877   8.4583        Q  
7   2.0      3      1            349909  21.0750        S

In [26]:
#DataFrame Drop NA based on Rows/Columns

d = df.dropna(subset=['Age'])
print(d.shape)
d.head()

(19, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
#Find the mean,median and mode values in the Age column
mean=df['Age'].mean()
median=df['Age'].median()
mode=df['Age'].mode()

In [28]:
# Replace Null Values (np.nan) with mean
df['Age'] = df['Age'].replace(np.nan, mean) #can be done for mean, median, mode
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [29]:
# Bakward fill
e = df.copy()
e['Cabin'] = e['Cabin'].fillna(method='bfill')
e.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   C85        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C123        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   E46        S

In [30]:
# Forward fill
f = df.copy()
f['Cabin'] = f['Cabin'].fillna(method='ffill')
f.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   C85        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  C123        S

In [31]:
# Most frequent values
df['Cabin'].value_counts()

D56     1
C103    1
G6      1
E46     1
C85     1
C123    1
Name: Cabin, dtype: int64

In [32]:
g = df.copy()
g['Cabin'] = g['Cabin'].fillna(g['Cabin'].value_counts().index[0])
g.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   D56        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   D56        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   D56        S

#### c.	To remove duplicate values in a dataset.

In [33]:
data = {'col1': [1, 1, 3, 3], 'col2': [1, 1, 3, 3], 'col3': [2, 2, 6, 5], 'col4': [2, 2, 6, 6]}

df = pd.DataFrame(data)
print('Source DataFrame:\n', df)

df.duplicated()

Source DataFrame:
    col1  col2  col3  col4
0     1     1     2     2
1     1     1     2     2
2     3     3     6     6
3     3     3     5     6


0    False
1     True
2    False
3    False
dtype: bool

In [34]:
#Drop Duplicate Rows Keeping the First One

df1 = df.copy()
dropped_df1 = df1.drop_duplicates()
print(dropped_df1)

   col1  col2  col3  col4
0     1     1     2     2
2     3     3     6     6
3     3     3     5     6


In [35]:
#Drop Duplicates and Keep Last Row

df2 = df.copy()
dropped_df2 = df2.drop_duplicates(keep='last')
print(dropped_df2)

   col1  col2  col3  col4
1     1     1     2     2
2     3     3     6     6
3     3     3     5     6


In [36]:
#Delete All Duplicate Rows from DataFrame

df3 = df.copy()
dropped_df3 = df3.drop_duplicates(keep=False)
print(dropped_df3)

   col1  col2  col3  col4
2     3     3     6     6
3     3     3     5     6


In [37]:
#Identify Duplicate Rows based on Specific Columns

df4 = df.copy()
dropped_df4 = df4.drop_duplicates(subset=['col1', 'col2'])
print(dropped_df4)

   col1  col2  col3  col4
0     1     1     2     2
2     3     3     6     6


In [38]:
#Remove Duplicate Rows in place

df5 = df.copy()
dropped_df5 = df5.drop_duplicates(inplace=True)
print(dropped_df5)

None
